sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t pijzl/vuejs-docker-unit-e2e:latest .
  - docker run -d -p 8080:8080 -v "$PWD":"$PWD" -w "$PWD" --name "vuejs-docker-unit-e2e" -it pijzl/vuejs-docker-unit-e2e:latest
  - docker ps -a
  - docker exec vuejs-docker-unit-e2e sh -c "cd my-vue-project && yarn"

script:
  - docker exec vuejs-docker-unit-e2e sh -c "cd my-vue-project && yarn test:unit && yarn test:e2e"